apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: juice-shop
spec:
  host: app-20-102-18-100.nip.io
  tls:
    secret: juice-shop-secret
  ingressClassName: rsampaiobb-nginx-ingress
  upstreams:
  - name: juice-shop
    service: juice-shop-svc
    port: 80
  routes:
  - path: /
    action:
      proxy:
        upstream: juice-shop
        requestHeaders:
          pass: true


